# Generated by Django 3.1 on 2020-08-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbv_todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('High', 'High Priority'), ('Low', 'Low Priority')], default='High', max_length=5),
        ),
    ]
