# Generated by Django 3.1 on 2020-08-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbv_todo', '0002_auto_20200830_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
